// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUDtLctVkQfz8pdqEYv4kaLEN6f7Puk5Y',
    appId: '1:143134033955:web:5ca4e42f6ff43aa6c30996',
    messagingSenderId: '143134033955',
    projectId: 'p-chess',
    authDomain: 'p-chess.firebaseapp.com',
    storageBucket: 'p-chess.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWVMURT0BVYGhpl-SkIYW5jdbCvLyvgB4',
    appId: '1:143134033955:android:b57a02eff26b6faac30996',
    messagingSenderId: '143134033955',
    projectId: 'p-chess',
    storageBucket: 'p-chess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAhqRo1s1t8XeWMpcGISzr6swKQ6QZL4',
    appId: '1:143134033955:ios:4143ec0ebf90d58ac30996',
    messagingSenderId: '143134033955',
    projectId: 'p-chess',
    storageBucket: 'p-chess.appspot.com',
    iosClientId: '143134033955-fevektn1n0t9cbe3g0ts1fb6cnubcq98.apps.googleusercontent.com',
    iosBundleId: 'tech.princepatel2206.pchess',
  );
}
